version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: petclinic/Dockerfile
    ports:
      - "8080:8080"
      - "6300:6300"
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/app/jacocoagent.jar=output=tcpserver,address=*,port=6300
    depends_on:
      - mysql
      - postgres
    networks:
      - petclinic-network

  mysql:
    image: mysql:9.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - petclinic-network

  postgres:
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_DB: petclinic
    networks:
      - petclinic-network
#extra line to ensure all services can communicate with each other inside Docker.
networks:
  petclinic-network:
    driver: bridge
