apiVersion: v1
kind: Service
metadata:
  name: rb-frontend-cluster-ip-service
  labels:
    service: rb-frontend
spec:
  type: ClusterIP
  selector:
    component: rb-frontend
  ports:
    - port: 80
      targetPort: 80
