<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by /var/www/html/claroline/inc/lib/config.class.php 
 * Date April 01, 2026 at 10:48 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLANNGenDate is an internal mark
   $CLANNGenDate = "1775033333";

/* announcementPortletMaxItems : Use 0 to display all */
$GLOBALS['announcementPortletMaxItems'] = 3;



?>