services:
  web:
    build: .
    container_name: brotherhood-web
    ports:
      - "8086:80"
    volumes:
      - ./src:/var/www/html
      # mount the shared scripts (read-only)
      - ./coverage-scripts:/coverage-scripts:ro
      # bind-mount output folder so coverage files appear on the host
      - ./coverage:/var/www/coverage
    depends_on:
      - db
    networks:
      - brotherhood-net

  db:
    image: mysql:5.5
    container_name: brotherhood-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brotherhood
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    #command: --sql-mode=""
    ports:
      - "3312:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - brotherhood-net

volumes:
  dbdata:

networks:
  brotherhood-net:
