<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by /var/www/html/claroline/inc/lib/config.class.php 
 * Date April 01, 2026 at 10:48 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLDSCGenDate is an internal mark
   $CLDSCGenDate = "1775033333";

/* cldsc_use_new_ordering_of_labels : Display description elements corresponding to others at the end */
$GLOBALS['cldsc_use_new_ordering_of_labels'] = FALSE;



?>