<?php 
/**  * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 * -------------------------------------------------
 * Generated by /var/www/html/claroline/inc/lib/config.class.php 
 * Date April 01, 2026 at 10:48 AM
 * -------------------------------------------------
 * DONT EDIT THIS FILE - NE MODIFIEZ PAS CE FICHIER 
 **/

// $CLWIKIGenDate is an internal mark
   $CLWIKIGenDate = "1775033333";

/* showWikiEditorToolbar : Show wiki syntax toolbar */
$GLOBALS['showWikiEditorToolbar'] = TRUE;


/* forcePreviewBeforeSaving : Force text preview before saving it */
$GLOBALS['forcePreviewBeforeSaving'] = FALSE;



?>